Traceback (most recent call last):
  File "C:\Users\aelshall\AppData\Local\miniconda3\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\aelshall\AppData\Local\miniconda3\Lib\site-packages\nbclient\client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aelshall\AppData\Local\miniconda3\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aelshall\AppData\Local\miniconda3\Lib\asyncio\base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\aelshall\AppData\Local\miniconda3\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\aelshall\AppData\Local\miniconda3\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\aelshall\AppData\Local\miniconda3\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Define a Python list containing two sublists representing rows of data
data = [[2, 4, 6, 8, 10],
        [0, 10, 20, 30, 40]]

# Convert the Python list 'data' to a NumPy array and assign it to the variable 'np_array'


# Print array type, shape, and values
print(np_array.dtype, np_array.shape)
print(np_array)
------------------


[31m---------------------------------------------------------------------------[39m
[31mNameError[39m                                 Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[7][39m[32m, line 9[39m
[32m      2[39m data = [[[32m2[39m, [32m4[39m, [32m6[39m, [32m8[39m, [32m10[39m],
[32m      3[39m         [[32m0[39m, [32m10[39m, [32m20[39m, [32m30[39m, [32m40[39m]]
[32m      5[39m [38;5;66;03m# Convert the Python list 'data' to a NumPy array and assign it to the variable 'np_array'[39;00m
[32m      6[39m 
[32m      7[39m 
[32m      8[39m [38;5;66;03m# Print array type, shape, and values[39;00m
[32m----> [39m[32m9[39m [38;5;28mprint[39m([43mnp_array[49m.dtype, np_array.shape)
[32m     10[39m [38;5;28mprint[39m(np_array)

[31mNameError[39m: name 'np_array' is not defined

