Traceback (most recent call last):
  File "C:\Users\aelshall\AppData\Local\miniconda3\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\aelshall\AppData\Local\miniconda3\Lib\site-packages\nbclient\client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aelshall\AppData\Local\miniconda3\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aelshall\AppData\Local\miniconda3\Lib\asyncio\base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\aelshall\AppData\Local\miniconda3\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\aelshall\AppData\Local\miniconda3\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\aelshall\AppData\Local\miniconda3\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Create a new column 'region' with default value 'Other'
df['REGION'] = 'Other'

# Mask for dicing: Define mask for Tampa Bay region based on latitude and longitude values

# Assign value 'Tampa Bay' to rows matching Tampa Bay mask 

# Mask for decing: Define mask for Charlotte Harbor estuary region  based on latitude and longitude values

# Assign value 'Charlotte Harbor' to rows matching Charlotte Harbor mask

#Display dataframe

------------------


[31m---------------------------------------------------------------------------[39m
[31mNameError[39m                                 Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[4][39m[32m, line 2[39m
[32m      1[39m [38;5;66;03m# Create a new column 'region' with default value 'Other'[39;00m
[32m----> [39m[32m2[39m [43mdf[49m[[33m'[39m[33mREGION[39m[33m'[39m] = [33m'[39m[33mOther[39m[33m'[39m
[32m      4[39m [38;5;66;03m# Mask for dicing: Define mask for Tampa Bay region based on latitude and longitude values[39;00m
[32m      5[39m 
[32m      6[39m [38;5;66;03m# Assign value 'Tampa Bay' to rows matching Tampa Bay mask [39;00m
[32m   (...)[39m[32m     11[39m 
[32m     12[39m [38;5;66;03m#Display dataframe[39;00m

[31mNameError[39m: name 'df' is not defined

